src/commands/diff.rs, src/commands/mark_upto_date.rs, src/commands/mod.rs, src/commands/start_tracking.rs, src/commands/status.rs, src/commands/stop_tracking.rs, src/commands/sync.rs, src/config.rs, src/document.rs, src/lib.rs, src/main.rs, src/snapshot.rs, src/tracker.rs, src/utils.rs, tests/01-help/cmd.p1, tests/08-hello-tracks/input/amitu/hello.txt
=> fpm commands

src/dependency.rs
…er. Also if declared translation need to declare language too
=> Check Added: both translation & translation-of can't be together, also language is required

fpm.js, ftd/fpm-lib.ftd, ftd/info.ftd, ftd/translation/missing.ftd, ftd/translation/never-marked.ftd, ftd/translation/out-of-date.ftd, ftd/translation/translation-status.ftd, src/library/mod.rs, src/utils.rs, tests/13-translation/output/FPM/translation-status/index.html, tests/13-translation/output/blog/index.html, tests/13-translation/output/db/index.html, tests/13-translation/output/index.html, tests/13-translation/output/lib/index.html, tests/14-translation-hindi/output/FPM/translation-status/index.html, tests/14-translation-hindi/output/index.html
All the values of fpm_ui moved to fpm.ui.
Some variables (mobile, dark-mode and follow-system-dark-mode) now become direct variables of fpm.
So you can do fpm.mobile, fpm.dark-mode and fpm.follow-system-dark-mode
=> fpm_ui -> fpm.ui

src/config.rs, src/dependency.rs, src/font.rs, src/library/mod.rs, tests/06-hello-font/input/amitu/.packages/one.fpm.local/FPM.ftd, tests/06-hello-font/input/amitu/FPM.ftd, tests/06-hello-font/input/amitu/index.ftd, tests/06-hello-font/output/-/index.html
=> Provision to use dependency fonts

src/commands/build.rs, src/config.rs, src/file.rs
`index.ftd` or `README.md` file inside a directory, lets say `<dir>`, would  converts to `<dir>/index.html`.
=> `index.ftd` file inside directory converts to `<dir>/index.html`

src/commands/update.rs, src/config.rs, src/main.rs
[Requirement PR](https://github.com/FifthTry/fpm.dev/pull/4)
=> config.root is now configurable

src/config.rs
[Requirement PR](https://github.com/FifthTry/fpm.dev/pull/5).
=> root for read should be string

ftd/design.ftd, tests/02-hello/input/amitu/index.ftd
Changes in typography tokens a/c to [link](https://github.com/sp0ck/ftd-design/blob/main/data/tokens.json)
=> Changes in typography tokens

ftd/design.ftd
=> updated custom color

ftd/design.ftd
Updated the color codes of background-base, background-step-1, background-step-2, text, cta-primary-base, cta-primary-disabled, cta-secondary-hover, cta-secondary-disabled, cta-tertiary-disabled, accent-primary.
=> color-update

Cargo.lock, Cargo.toml, ftd/fpm.ftd, src/commands/build.rs, src/config.rs, src/dependency.rs, src/file.rs, src/lib.rs, src/library/get_data.rs, src/library/get_sitemap.rs, src/library/mod.rs, src/library/toc.rs, src/sitemap.rs, tests/02-hello/output/-/index.html, tests/02-hello/output/index.html, tests/03-nested-document/output/-/index.html, tests/04-import-package-doc/output/-/index.html, tests/15-recursive-download-dependencies/output/-/index.html, tests/17-fpm-dependency-alias/output/-/index.html, tests/17-fpm-dependency-alias/output/index.html, tests/18-include-processor/output/-/index.html, tests/19-dependency-alias-prelude/output/-/index.html, tests/19-dependency-alias-prelude/output/static_main.txt/index.html
[Doc PR](https://github.com/FifthTry/fpm.dev/pull/15)
=> FPM sitemap

Cargo.lock, Cargo.toml, README.md, src/commands/mod.rs, src/commands/serve.rs, src/lib.rs, src/main.rs, tests/01-help/cmd.p1
- [Docs PR](https://github.com/FifthTry/fpm.dev/pull/13)
=> added http server for serving static files

ftd/fpm.ftd, src/library/get_sitemap.rs, src/sitemap.rs
[Doc PR](https://github.com/FifthTry/fpm.dev/pull/20/)
=> Added current section, current subsection and current_page

Cargo.lock, src/commands/build.rs, src/config.rs
`md` files can also be added to the sitemap in the same manner as the `FTD` files
=> `md` files can be added in sitemap

ftd/design.ftd
changed line height of heading-hero from '52' to '60'
=> changed line height of heading-hero from '52' to '60'

src/sitemap.rs
[Feature Task](https://github.com/FifthTry/fpm/issues/206)
=> skip section, subsection and toc

src/commands/serve.rs, src/main.rs
`fpm cli` will automatically pick a port between 8000 to 9000, if a provided port is not available.
=> `fpm cli` pick available port

Cargo.lock, Cargo.toml
=> added ftd - d5f5ba6

ftd/editor.ftd
Updated editor UI with basic UI, as discussed!
=> updating editor UI with new editor UI designs

ftd/editor.ftd
Added image from fpm-editor package
e.g.
https://fifthtry.github.io/fpm-editor/-/fifthtry.github.io/fpm-editor/mobile-frame.png
=> updating image urls from fpm-editor package

ftd/editor.ftd
updated green background issue and spacing between sub-folders and all
=> updating UI for left nav

ftd/editor.ftd
Updated fpm-editor package name link to fpm-ui
=> updated fpm-ui package name image path

ftd/editor.ftd
safari issue of texture is fixed with adding white-space: pre
=> Fpm UI name change

ftd/editor.ftd
added nesting for sub-folder file names with 12px
=> added nesting to sub-folder files

ftd/editor.ftd
Added new features as below to fpm editor:
1. Added new file and folder icons onto folder mouseover
2. Changed All files titlebar with tabs - All files and Sitemap
3. Added vertical 80 chars guideline - activates if user editing file
4. Few alignments issues fixed of file-icon and folder right and down arrows
5. New Folder - dialog added
6. New File - dialog added
7. Sitemap: - mouseover tooltip - nested sitemap and alignments
=> Added new features to editor

ftd/editor.ftd
Editor updated with new UI features as below: Added show-cr-ui global variable to show/hide CR ui
1. CR UI added
2. CR toc added
3. M - modifications -  active state UI added
4. E - Error - active state UI added
5. All files | Sitemap - tabs UI updated
6. Mobile UI fixed of all above changes
=> Added CR UI and updated tabs UI with M E ui

ftd/design.ftd
=> updating default colors

ftd/fpm.ftd, src/config.rs, src/library/full_sitemap.rs, src/library/mod.rs, src/library/package_tree.rs, src/library/sitemap.rs, src/sitemap.rs, src/user_group.rs
[Doc PR](https://github.com/FifthTry/fpm.dev/pull/52)
=> readers writers definition in sitemap

src/apis/sync2.rs, src/commands/resolve_conflict.rs, src/commands/sync2.rs, src/commands/sync_status.rs, src/sync_utils.rs
[Doc PR](https://github.com/FifthTry/fpm.dev/pull/62/)
=> add-add-conflict

Cargo.lock, Cargo.toml
=> updated ftd in cargo

ftd/design.ftd
With this change we have added light-mode background colors. Below sample screen-shot of fpm.dev shows how it will look on light-mode!
=> Introducing light mode colors

Cargo.lock, Cargo.toml
Use latest FTD from `0c9ab21` - and create new release of FPM with `0c9ab21`
=> Using latest ftd: `0c9ab21`

tests/17-fpm-dependency-alias/input/amitu/.packages/fifthtry.github.io/blog-theme/index.ftd
- fixed duplicate header issue inside fbt
=> dup header fix in fbt test-17

ftd/fpm.ftd, src/apis/clone.rs, src/cache/mod.rs, src/commands/add.rs, src/commands/clone.rs, src/commands/close_cr.rs, src/commands/create_cr.rs, src/commands/mod.rs, src/commands/sync2.rs, src/config.rs, src/cr.rs, src/history.rs, src/lib.rs, src/main.rs, src/sync_utils.rs, src/workspace.rs, tests/01-help/cmd.p1
[Doc PR](https://github.com/FifthTry/fpm.dev/pull/48/files)
=> `fpm create-cr`, `fpm add`, `fpm close-cr`

src/apis/clone.rs, src/apis/edit.rs, src/apis/sync.rs, src/apis/sync2.rs, src/apis/view_source.rs, src/commands/build.rs, src/commands/build2.rs, src/commands/clone.rs, src/commands/serve.rs, src/commands/update.rs, src/config.rs, src/controller.rs, src/dependency.rs, src/doc.rs, src/library/full_sitemap.rs, src/library/get_data.rs, src/library/mod.rs, src/library/sitemap.rs, src/main.rs, src/package_doc.rs, src/user_group.rs
[Doc PR](https://github.com/FifthTry/fpm.dev/pull/66)
=> Code Refactor(move `fpm::Config.sitemap`, `fpm::Config.groups` to `fpm::Package`)

src/main.rs
=> redundant-code fix

ftd/editor.ftd
We observed few editor issues while testing editor!
fixed them via this PR. @amitu Please, merge this PR.
=> Fixing few UI issues observed in editor

ftd/design.ftd
let's revert light mode color changes, until dark and light mode feature is live.
=> reverting all changes of light mode colors

src/config.rs
- included both conflicting docs in the error msg in case same id (user defined) is used again at the package level.
=> conflicting global id error msg adjustment

src/commands/serve.rs
[Main PR](https://github.com/FifthTry/fpm/pull/467)
[Discussion](https://github.com/FifthTry/fpm/discussions/475)
=> Fix drop: variable declared with was getting dropped immediately

src/commands/serve.rs, src/http.rs, src/lib.rs, src/proxy.rs
[Discussion](https://github.com/FifthTry/fpm/discussions/462)
=> Proxy Endpoint Support

src/sitemap.rs
- fixed issue with linking when url's of type `<doc-id>#<id>` are used in sitemap
=> Sitemap linking fix

Cargo.lock, Cargo.toml, src/config.rs, src/doc.rs
- changed to adjust with the latest linking syntax adjustments in `FTD`
=> Check-Id Adjustments

src/commands/serve.rs, src/config.rs, src/http.rs, src/lib.rs, src/library/http.rs, src/library/mod.rs, src/proxy.rs
[Discussion](https://github.com/FifthTry/fpm/discussions/516)
[Doc PR](https://github.com/FifthTry/fpm.dev/pull/85)
=> `request-data` processor

src/config.rs, src/sitemap.rs
[FPM Discussion](https://github.com/FifthTry/fpm/discussions/518)
- added id attribute to be used for linking within sitemap
=> Sitemap linking support using id

ftd/fpm.ftd, src/commands/serve.rs, src/config.rs, src/dependency.rs, src/library/http.rs, src/proxy.rs, src/sitemap.rs
[Discussion](https://github.com/FifthTry/fpm/discussions/462)
=> Proxy Endpoint

ftd/fpm.ftd, src/commands/serve.rs, src/config.rs, src/library/get_version_data.rs, src/library/toc.rs, src/sitemap.rs, tests/20-sitemap/output/-/index-alias/index.html, tests/20-sitemap/output/childtoc/index.html, tests/20-sitemap/output/index.html, tests/20-sitemap/output/section/index.html, tests/20-sitemap/output/subsection/-/arpita/index.html, tests/20-sitemap/output/subsection/index.html, tests/20-sitemap/output/toc/index.html
[Discussion](https://github.com/ftd-lang/fpm/discussions/465)
=> `document` mapping in Sitemap

Cargo.lock, Cargo.toml
- updated ftd version -> d0694ed
=> bumped ftd version 

Cargo.lock, Cargo.toml, src/commands/serve.rs, src/config.rs, src/error.rs, src/http.rs, src/lib.rs, src/library/http.rs, src/sitemap.rs
[Discussion](https://github.com/ftd-lang/fpm/discussions/551)
[Doc](https://github.com/ftd-lang/fpm.dev/pull/89)
=> `named-params` support in `request-data` processor

src/lib.rs, src/library/full_sitemap.rs, src/library/package_tree.rs, src/sitemap/mod.rs, src/sitemap/section.rs, src/sitemap/toc.rs, src/sitemap/utils.rs
https://github.com/ftd-lang/fpm/discussions/569
=> sitemap/refactor: move code to separate mod

ftd/fpm.ftd, src/library/package_tree.rs, src/sitemap/dynamic_urls.rs, src/sitemap/mod.rs, src/sitemap/section.rs, src/sitemap/toc.rs
- added icon attribute in sitemap
=> Icon for sitemap elements

.rusty-hook.toml, src/commands/serve.rs, src/config/mod.rs, src/config/utils.rs, src/http.rs, src/package/mod.rs, src/proxy.rs, src/sitemap/mod.rs, src/sitemap/section.rs
- [Discussion](https://github.com/ftd-lang/fpm/discussions/462)
- Docs: Pending
=> redirect request if mount-point present

.rusty-hook.toml, ftd/fpm.ftd, src/commands/serve.rs, src/config/mod.rs, src/config/utils.rs, src/http.rs, src/library/http.rs, src/package/mod.rs, src/proxy.rs
Discussion: https://github.com/ftd-lang/fpm/discussions/599
Docs: Pending
=> multi mount-point

ftd/fpm.ftd, src/auth/processor.rs, src/library/mod.rs, src/package/app.rs, src/package/mod.rs
Discussion: https://github.com/ftd-lang/fpm/discussions/599
Docs: https://github.com/ftd-lang/fpm.dev/pull/93
=> `fpm-apps` Processor

ftd/fpm.ftd, src/commands/serve.rs, src/config/mod.rs, src/config/utils.rs, src/package/app.rs
Discussion: https://github.com/ftd-lang/fpm/discussions/599
=> `fpm.app` readers

ftd/fpm.ftd, src/commands/serve.rs, src/config/mod.rs, src/config/utils.rs, src/ds.rs, src/file.rs, src/lib.rs, src/package/app.rs, src/package/mod.rs
Docs: https://github.com/ftd-lang/fpm.dev/pull/94
Discussion: https://github.com/ftd-lang/fpm/discussions/599
=> FPM Apps Fixes/Added Package Icon/Redirect Fixes for Images

src/auth/github.rs, src/commands/serve.rs
=> contributor and collaborator

ftd/fpm.ftd, src/auth/github.rs, src/commands/serve.rs, src/package/user_group.rs
github-watch to github-watches-conflicts
=> github-watch to github-watches

src/commands/serve.rs, src/config/mod.rs, src/library/mod.rs, src/library/sitemap.rs, src/package/user_group.rs, src/sitemap/mod.rs, src/sitemap/section.rs, src/sitemap/toc.rs
Discussion: https://github.com/ftd-lang/fpm/discussions/409
=> Sitemap `confidential` property

ftd/design.ftd
Added mobile and desktop device typo. As of now it's same for all - in future we will change as per device sizes.
=> Added mobile and xl typo copies

Cargo.lock, Cargo.toml, src/auth/telegram.rs, src/commands/serve.rs, src/lib.rs
We are commenting out the `wasmtime` and it's a dependency for some time, we will bring it back with more power and more strongly.
=> Commented Wasmtime 

ftd/fpm.ftd, src/auth/discord.rs, src/auth/github.rs, src/auth/mod.rs, src/auth/routes.rs, src/auth/telegram.rs, src/auth/utils.rs, src/package/user_group.rs
[Discussion](https://github.com/ftd-lang/fpm/discussions/663)
=> discord authorization

ftd/fpm.ftd, src/auth/github.rs, src/auth/mod.rs, src/commands/serve.rs, src/config/utils.rs, src/library/http.rs, src/package/app.rs, src/proxy.rs
- added x-fpm-user-id header in proxy and http processor
=> added x-fpm-user-id header

Cargo.lock, Cargo.toml
- updated ftd version after adding ftd.region (v0.3)
- updated changelogs and cheatsheet
=> updated ftd version having updated changelogs

Cargo.lock, Cargo.toml, examples/performance/scripts/sitemap-template.ftd, src/doc.rs
[FTD PR](https://github.com/ftd-lang/ftd/pull/542)
=> Cache for `ftd` Parsed Docs
